"""empty message

Revision ID: 172067bbbf34
Revises: a695ce20e332
Create Date: 2024-07-16 19:02:33.940304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172067bbbf34'
down_revision = 'a695ce20e332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(length=10), nullable=False))
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        # Add back the end_date column with nullable=True
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        
        # Alter the start_date column to its original type and constraints
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.DateTime(),
               existing_nullable=False)
        
        # Drop the temporary columns
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###