"""add feeds to communities

Revision ID: 3d3cb5d7d939
Revises: ebc2eb119036
Create Date: 2024-07-17 21:11:43.357804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3cb5d7d939'
down_revision = 'ebc2eb119036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_feeds_community_id', 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feeds_community_id', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
