"""empty message

Revision ID: d608f5852135
Revises: 82ef4ab7cbf1
Create Date: 2024-07-10 23:21:58.972435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd608f5852135'
down_revision = '82ef4ab7cbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_products_user', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
